travis:
  secure:
    BINSTAR_TOKEN: dUhbCWNVH/buw3rY/G5bWtevguxs/JZnrmhxDKkx42c7xijzjNBUwzUcOnSxyZxkhuDzXhgTvCIqE75TJIMJ00bc4W0FJIuLC0ZPv6IkCbkG3FQ4mAo0x+9zswTtYl+8/KT3NleE+3QN5psOwAJuZkhfKwHzfhmGU5hD/2b6mNdTyS1+zuhGEb3LhZkEyDyXUotJFm36W5ypYWD9U1RlkSZg/9bscdxqm9ZovIePqoRXFsHLtQVS574URwjKDZdt/k1gA59jghTn2f2QnxS1ZJW2/byr+DJ6ArT75iA4xTzfkmURgRv4Ue3TJB6sJuzbv07BdSsHARq88qsqsJVGGHbidO6LDBeyn9YpLtNdkJtdB7QkHIXyXV5oBLIE19cWNHQ2NRykB3IGIRoTwBjcbK8zFetgbFqztjvtXXyTd1nCRUcVBvaxW6UsrXkm3KdGbVSdnFzDwPR4O/pK+FvF6ao/CmYParMZv096f76b5Z5Zp2av60Cdk46neiGdB3sV3s9wc+nKRNRaMp+PKspDiZgwpjE8uxe+PixZ8sSVpMwHiBgmFwLiyXkO6TPQforvTSjKPdq6EYwt/pE8ytEqSJOg5hoVFVXfZ2ke6ZLzHmv3AJCWMGwwBBI7fBkCKloK1M7IfhohiRLwEAbW1v/Oya8GcbuyiY2uF72x46gxQ6w=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
