travis:
  secure:
    BINSTAR_TOKEN: nrKH/B2iX/F+wXz8fQUA9x2mWQ+Dide0ZnBJ7CWW9ng7kwDbSRy9rFxhGoBE6oRwFbMlg0yWdgzCvp6PzAq7UsFIcqbvMv6LwWFTfLs11DQ5nocAFjHSM6YEixeDYjgd8rF7pyRPEIFii+rjV4R0fE4NJ6AJMIda1KP7revxbqvPzuYx1okkWCvF16BS8kdwxnSaxOTgndf11X2lOmhLie1IZ7e2wk0fV4Bp018cqWDV1Mgequwkry5Ib3FLDx+cc+LRyfhphESQoVXbu350CqNsdDakvX+Ez3Ep6Z98c0O+OehheBhtO+V0mYJ2yL9Qtv+h91aWtdDqX995eDL/OvaBYbQbv36LLdxqtyA8EfCRLxnfQjp6dVuYQdHu2pWepvn4YO5xhWNXBz7wJ22pRdrrmiSe8GOrIDnHxE5R3CxgFphR+HvNys46cWc4uodv3EKTphPwBcF1U1NIAFcs0RB+LgrtWgXqJJHkd8LCJLtC/WJHzf6F21etGCMlrYe5AaHgbDbR7iuRuk/VT0k/xnMTU/JKIUkrX6YzIow165hMOv0EG7pAs/stzKjbFAQTYvTy2BATP7V7xEezvvLq/ohmbBK/AAjVlADauUDPmsXe4gpFtJk/712Jr1qA0R0rBmO6sI7TAPph0ZmdRDGG4F9leD6fPxaNalCDm6mfvsQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
